### ISSUE TITLE
Host www2.dgi.inpe.br indisponivel

### ISSUE THREAD

**Issue by vivianmarcello** [gabriel-russo/cbers4asat#12]
Estou recebendo esta mensagem quando tento baixar uma imagem usando a biblioteca. 
ConnectionError: HTTPConnectionPool(host='www2.dgi.inpe.br', port=80): Max retries exceeded with url: /inpe-stac/search (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by gabriel-russo** [comment]
Bom dia vivian!, agradeço a issue!

Nesses ultimos dias o INPE está com alguns de seus serviços fora do ar por causa de um ataque hacker, inclusive o catálogo de imagens do CBERS-04A...

[Abri uma Discussão](https://github.com/gabriel-russo/cbers4asat/discussions/11) na aba de Discussões aqui do repositório e estou de olho diariamente no status dos serviços para avisar lá quando voltar.

O ocorrido foi noticiado no link abaixo... foi publicado dia 01/08/2023 e não houve nenhum retorno até agora

https://www.gov.br/inpe/pt-br/assuntos/ultimas-noticias/nota-a-imprensa-sobre-o-catalogo-de-imagens

Qualquer outra dúvida, estou a disposição

**Comment by vivianmarcello** [comment]
Boa tarde, Gabriel!

Obrigada pelo rápido retorno. 
Vou ficar acompanhando!
