### ISSUE TITLE
Criar algoritmos de processamento digital de imagens

### ISSUE THREAD

**Issue by gabriel-russo** [gabriel-russo/cbers4asat#4]
Esse módulo desse ser implementado separadamente do arquivo `cbers4asat.py` e ser encapsulado em um módulo chamado `tools`.

Esses algoritmos serão oferecidos como opcionais ao usuário.

Alguns algoritmos a serem implementados:

- [x] Pansharp (Banda 0)
- [x] Stack de bandas (Bandas 1, 2, 3, 4)
- [x] Clip de raster

**Comment by gabriel-russo** [comment]
Stack de bandas: d2075f3bfc0e54d003d3abd844f07c3434dbf7ba

**Comment by gabriel-russo** [comment]
Pansharp: 31a7bab17df3d04806a4d275f4471782cc88d481

**Comment by gabriel-russo** [comment]
Clip de raster: ca11df18910bf0fd83b3186fc5261e3cb77e14cc

**Comment by BerniniH** [comment]
Não vai deixar nada pro pai se exercitar!
